/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Java_Project_1;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.function.Function;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shahryar
 */
public class Window_first extends javax.swing.JFrame {

    /**
     * Creates new form Window_first
     */
    public Window_first() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
       // JScrollPane pane = new JScrollPane(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

//        this.setContentPane(pane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        btn_DB = new javax.swing.JButton();
        btn_BS = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        lbl_price = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_img = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        lbl_image = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTable_Products = new javax.swing.JTable();
        Btn_Choose_Image = new javax.swing.JButton();
        btn_Insert = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_First = new javax.swing.JButton();
        btn_Next = new javax.swing.JButton();
        btn_Previous = new javax.swing.JButton();
        btn_Last = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        lbl_background = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Price2 = new javax.swing.JTextField();
        txt_Per_UC = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        JTable_bill = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txt_ID2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Name2 = new javax.swing.JTextField();
        btn_add_bill = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_NP1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_sum = new javax.swing.JTextField();
        btn_Exit1 = new javax.swing.JButton();
        lbl_background1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1900, 973));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1600, 900));

        jPanel2.setLayout(null);

        btn_DB.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_DB.setText("PRODUCT DATABASE");
        btn_DB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DBActionPerformed(evt);
            }
        });
        jPanel2.add(btn_DB);
        btn_DB.setBounds(20, 700, 230, 50);

        btn_BS.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_BS.setText("BILLING SYSTEM");
        btn_BS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BSActionPerformed(evt);
            }
        });
        jPanel2.add(btn_BS);
        btn_BS.setBounds(550, 700, 180, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/data4.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 610, 70, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/billorg.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(600, 610, 90, 64);

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HB COMPUTER MANAGEMENT SYSTEM");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 500, 760, 50);

        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.setIconTextGap(10);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel2.add(btn_exit);
        btn_exit.setBounds(330, 810, 120, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg2.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1600, 900);

        jScrollPane1.setViewportView(jPanel2);

        jTabbedPane1.addTab("tab1", jScrollPane1);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setText("Name:");
        jPanel3.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        lbl_price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_price.setForeground(new java.awt.Color(255, 255, 255));
        lbl_price.setText("Price:");
        jPanel3.add(lbl_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        lbl_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id.setText("ID:");
        jPanel3.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 50, -1, -1));

        lbl_date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(255, 255, 255));
        lbl_date.setText("Add Date:");
        jPanel3.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        lbl_img.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_img.setForeground(new java.awt.Color(255, 255, 255));
        lbl_img.setText("Image:");
        jPanel3.add(lbl_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        txt_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        jPanel3.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 164, 34));

        txt_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_id.setName("ID"); // NOI18N
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel3.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 46, 92, 34));

        txt_price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_priceActionPerformed(evt);
            }
        });
        jPanel3.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 164, 34));

        lbl_image.setBackground(new java.awt.Color(255, 255, 255));
        lbl_image.setOpaque(true);
        jPanel3.add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 267, 204));

        JTable_Products.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JTable_Products.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        JTable_Products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Date"
            }
        ));
        JTable_Products.setToolTipText("");
        JTable_Products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_ProductsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(JTable_Products);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 610, 490));

        Btn_Choose_Image.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Choose_Image.setText("Choose Image");
        Btn_Choose_Image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Choose_ImageActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Choose_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 164, 33));

        btn_Insert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add1.png"))); // NOI18N
        btn_Insert.setText("Insert");
        btn_Insert.setIconTextGap(15);
        btn_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsertActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 113, 34));

        btn_Delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete1.png"))); // NOI18N
        btn_Delete.setText("Delete");
        btn_Delete.setIconTextGap(15);
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 113, 34));

        btn_First.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_First.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/first.png"))); // NOI18N
        btn_First.setText("First");
        btn_First.setIconTextGap(15);
        btn_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FirstActionPerformed(evt);
            }
        });
        jPanel3.add(btn_First, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 630, 113, 34));

        btn_Next.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/next.png"))); // NOI18N
        btn_Next.setText("Next");
        btn_Next.setIconTextGap(15);
        btn_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NextActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 630, 113, 34));

        btn_Previous.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pre.png"))); // NOI18N
        btn_Previous.setText("Previous");
        btn_Previous.setIconTextGap(15);
        btn_Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PreviousActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 630, -1, 34));

        btn_Last.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Last.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/last.png"))); // NOI18N
        btn_Last.setText("Last");
        btn_Last.setIconTextGap(15);
        btn_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LastActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Last, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 630, 113, 34));

        btn_Update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update1.png"))); // NOI18N
        btn_Update.setText("Update");
        btn_Update.setIconTextGap(15);
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 113, 34));

        btn_Exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        btn_Exit.setText("EXIT");
        btn_Exit.setIconTextGap(8);
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 810, -1, 30));

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg2.jpg"))); // NOI18N
        lbl_background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_backgroundMouseReleased(evt);
            }
        });
        jPanel3.add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1615, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel1);

        jScrollPane4.setPreferredSize(new java.awt.Dimension(1600, 900));

        jPanel5.setPreferredSize(new java.awt.Dimension(1600, 900));

        jPanel6.setBackground(new java.awt.Color(255, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product ID:");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Per Unit Cost:");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 31));

        txt_Price2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Price2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Price2ActionPerformed(evt);
            }
        });
        jPanel6.add(txt_Price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 146, 40));

        txt_Per_UC.setEditable(false);
        txt_Per_UC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Per_UC.setEnabled(false);
        txt_Per_UC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Per_UCActionPerformed(evt);
            }
        });
        jPanel6.add(txt_Per_UC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 146, 40));

        btn_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_add.setForeground(new java.awt.Color(51, 51, 51));
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add1.png"))); // NOI18N
        btn_add.setText("ADD");
        btn_add.setBorder(null);
        btn_add.setIconTextGap(15);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel6.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 102, 45));

        JTable_bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "PRICE", "PIECES", "TOTAL"
            }
        ));
        jScrollPane5.setViewportView(JTable_bill);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 690, 420));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Price:");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        txt_ID2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ID2ActionPerformed(evt);
            }
        });
        jPanel6.add(txt_ID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 146, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name:");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txt_Name2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Name2ActionPerformed(evt);
            }
        });
        jPanel6.add(txt_Name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 146, 40));

        btn_add_bill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_add_bill.setForeground(new java.awt.Color(51, 51, 51));
        btn_add_bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add1.png"))); // NOI18N
        btn_add_bill.setText("ADD TO BILL");
        btn_add_bill.setBorder(null);
        btn_add_bill.setIconTextGap(15);
        btn_add_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_billActionPerformed(evt);
            }
        });
        jPanel6.add(btn_add_bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 190, 45));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("No Of Pieces:");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 122, 31));

        txt_NP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_NP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NP1ActionPerformed(evt);
            }
        });
        jPanel6.add(txt_NP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 146, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TOTAL BILL:");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 510, -1, 27));

        txt_sum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sumActionPerformed(evt);
            }
        });
        jPanel6.add(txt_sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 510, 90, 35));

        btn_Exit1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        btn_Exit1.setText("EXIT");
        btn_Exit1.setIconTextGap(8);
        btn_Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Exit1ActionPerformed(evt);
            }
        });
        jPanel6.add(btn_Exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 760, -1, 30));

        lbl_background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg2.jpg"))); // NOI18N
        jPanel6.add(lbl_background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1615, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab3", jPanel4);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
  String imgPath=null;
  int pos = 0;
    
    
    
  
    public Connection getConnection()
    {
        Connection con=null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/products_db2", "root", "");
           // JOptionPane.showMessageDialog(null, "Connected");
            return con;
        } 
        catch (SQLException ex) {
            //Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Not Connected");
            return null;
        }
               
    }
    
    //check input fields
    public boolean checkInputs()
    {
        if(
              txt_name.getText() == null
           || txt_price.getText() == null
         //  || txt_AddDate == null
          ){
            return false;
        }
        else{
            try{
                Float.parseFloat(txt_price.getText());
                return true;
            }catch(Exception ex)
            {
                return false;
            }
        }
    }
    
    
    
    //image resize
    public ImageIcon ResizeImage(String imagePath,byte[] pic)
    {
        ImageIcon myImage =null;
        
        if(imagePath != null)
        {
            myImage = new ImageIcon(imagePath);
            
        }else{
            myImage = new ImageIcon(pic);
        }
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lbl_image.getWidth(),lbl_image.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }
    
    //Display Data in Jtable
    //  1 - FillArray with Data
    
    public ArrayList<Product> getProductList()
    {
            ArrayList<Product> productList = new ArrayList<Product>();
            Connection con = getConnection();
            String query ="SELECT * FROM products";
            Statement st;
            ResultSet rs;
        try {
            
            st = con.createStatement();
            rs= st.executeQuery(query);
            Product product;
            
            while(rs.next())
            {
                product = new Product(rs.getInt("id"),rs.getString("name"),Float.parseFloat(rs.getString("price")),rs.getString("add_date"),rs.getBytes("image"));
                productList.add(product);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Window_first.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return productList;
        
        
    }
    
    
    //  2 - Populate the Jtable
    
    public void Show_Products_In_JTable()
    {
        ArrayList<Product> list = getProductList();
        DefaultTableModel model = (DefaultTableModel)JTable_Products.getModel();
        
        model.setRowCount(0);
        Object[] row = new Object[4];
        for(int i=0; i<list.size();i++)
        {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getPrice();
            row[3] = list.get(i).getAddDate();
            
            model.addRow(row);
        }
        
    }
    
    
    public void ShowItems(int index)
    {
        txt_id.setText(Integer.toString(getProductList().get(index).getId()));
        txt_name.setText(getProductList().get(index).getName());
        txt_price.setText(Float.toString(getProductList().get(index).getPrice()));
        
       
     
        
         /*   try {
           Date addDate = null;
            addDate = (Date) new SimpleDateFormat("MM-DD-YYYY").parse((String)getProductList().get(index).getAddDate());
            txt_AddDate.setDate(addDate);
        } catch (ParseException ex) {
            Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
        
        lbl_image.setIcon(ResizeImage(null, getProductList().get(index).getImage()));
        
        
        
    }
            
            
            
            
  
  
  
  
    
    
    private void btn_DBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DBActionPerformed
      
       
        
    }//GEN-LAST:event_btn_DBActionPerformed

    private void btn_BSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BSActionPerformed
        
       
    }//GEN-LAST:event_btn_BSActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
       
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_priceActionPerformed

    private void JTable_ProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_ProductsMouseClicked
        // TODO add your handling code here:
        int index = JTable_Products.getSelectedRow();
        ShowItems(index);

    }//GEN-LAST:event_JTable_ProductsMouseClicked

    private void Btn_Choose_ImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Choose_ImageActionPerformed
        // TODO add your handling code here:

        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        //if the user click on save in Jfilechooser
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lbl_image.setIcon(ResizeImage(path,null));
            imgPath = path;
        }
        //if the user click on save in Jfilechooser

        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No File Select");
        }

    }//GEN-LAST:event_Btn_Choose_ImageActionPerformed

    private void btn_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertActionPerformed
        // TODO add your handling code here:
        if(checkInputs() && imgPath!=null)
        {

            try {
                Connection con= getConnection();
                PreparedStatement ps= con.prepareStatement("INSERT INTO products(name,price,add_date,image)"+"values(?,?,?,?) ");
                ps.setString(1, txt_name.getText());
                ps.setString(2, txt_price.getText());

                //Date date = new Date(0);
                //SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd");
                // String addDate = dateFormat.format(txt_AddDate.getDate());
                // ps.setString(3, addDate);

                //  ps.setDate(3, date.valueOf("1998-1-17"));

                // java.sql.Date date = getCurrentJavaSqlDate();
                // ps.setDate(2, date);

                java.sql.Timestamp date = new java.sql.Timestamp(new java.util.Date().getTime());
                ps.setTimestamp(3, date);

                InputStream img = new FileInputStream(new File(imgPath));
                ps.setBlob(4,img);
                ps.executeUpdate();
                Show_Products_In_JTable();

                JOptionPane.showMessageDialog(null, "Data Inserted");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null,"One or More Fields Are Empty");
        }

        System.out.println("Name =>"+txt_name.getText());
        System.out.println("Price =>"+txt_price.getText());
        System.out.println("Image =>"+imgPath);

    }//GEN-LAST:event_btn_InsertActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:

        if(!txt_id.getText().equals(""))
        {
            try {
                Connection con = getConnection();
                PreparedStatement ps = con.prepareStatement("DELETE FROM products WHERE id = ?");
                int id = Integer.parseInt(txt_id.getText());
                ps.setInt(1, id);
                ps.executeUpdate();
                Show_Products_In_JTable();
                JOptionPane.showMessageDialog(null, "Product Deleted");

            } catch (SQLException ex) {
                Logger.getLogger(Window_first.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Product Not Deleted");
            }
        }else{

            JOptionPane.showMessageDialog(null, "Product Not Deleted : No ID to Delete");
        }

    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FirstActionPerformed
        // TODO add your handling code here:
        pos = 0;
        ShowItems(pos);

    }//GEN-LAST:event_btn_FirstActionPerformed

    private void btn_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextActionPerformed
        // TODO add your handling code here:
        pos++;
        if(pos >= getProductList().size())
        {
            pos = getProductList().size()-1;
        }
        ShowItems(pos);

    }//GEN-LAST:event_btn_NextActionPerformed

    private void btn_PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PreviousActionPerformed
        // TODO add your handling code here:
        pos--;
        if(pos < 0)
        {
            pos = 0;
        }
        ShowItems(pos);
    }//GEN-LAST:event_btn_PreviousActionPerformed

    private void btn_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LastActionPerformed
        // TODO add your handling code here:
        pos = getProductList().size()-1;
        ShowItems(pos);

    }//GEN-LAST:event_btn_LastActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        if(checkInputs() && txt_id.getText() != null)
        {
            String UpdateQuery = null;
            PreparedStatement ps = null;
            Connection con = getConnection();

            //update without image

            if(imgPath == null)
            {
                try {
                    UpdateQuery= "UPDATE products SET name= ?, price = ?"
                    +",add_date = ? WHERE id = ?";
                    ps = con.prepareStatement(UpdateQuery);

                    ps.setString(1, txt_name.getText());
                    ps.setString(2 , txt_price.getText());

                    //  SimpleDateFormat dateFormat = new SimpleDateFormat("MM-DD-YYYY");
                    // String addDate = dateFormat.format(txt_AddDate.getDateFormat())

                    java.sql.Timestamp date = new java.sql.Timestamp(new java.util.Date().getTime());
                    ps.setTimestamp(3, date);

                    ps.setInt(4, Integer.parseInt(txt_id.getText()));
                    ps.executeUpdate();
                    Show_Products_In_JTable();
                    JOptionPane.showMessageDialog(null,"Product Updated");

                } catch (SQLException ex) {
                    Logger.getLogger(Window_first.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            //update with image
            else{
                try{
                    InputStream img = new FileInputStream(new File(imgPath));

                    UpdateQuery= "UPDATE products SET name= ?, price = ?"
                    +", add_date = ?,image = ? WHERE id = ?";

                    ps = con.prepareStatement(UpdateQuery);

                    ps.setString(1, txt_name.getText());
                    ps.setString(2 , txt_price.getText());

                    //  SimpleDateFormat dateFormat = new SimpleDateFormat("MM-DD-YYYY");
                    // String addDate = dateFormat.format(txt_AddDate.getDateFormat())

                    java.sql.Timestamp date = new java.sql.Timestamp(new java.util.Date().getTime());
                    ps.setTimestamp(3, date);

                    ps.setBlob(4, img);

                    ps.setInt(5, Integer.parseInt(txt_id.getText()));
                    ps.executeUpdate();
                    Show_Products_In_JTable();
                    JOptionPane.showMessageDialog(null,"Product Updated");

                }catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "One or More Fields Are Empty or Wrong");

        }

    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void lbl_backgroundMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backgroundMouseReleased

      /*  if(evt.isPopupTrigger())
        {
            RC_menu.show(this,evt.getX(),evt.getY());
        }*/

    }//GEN-LAST:event_lbl_backgroundMouseReleased

    private void txt_Price2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Price2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Price2ActionPerformed

    private void txt_Per_UCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Per_UCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Per_UCActionPerformed

    
    
        public class Function{
        
        Connection con = null;
        ResultSet rs = null;
        PreparedStatement ps = null;
        
        public ResultSet find(String s)
        {
            try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/products_db2", "root", "");
            ps= con.prepareStatement("SELECT * from products WHERE id= ?");
            ps.setString(1, s);
            rs = ps.executeQuery();
            }catch(Exception ex ){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            return rs;
            
        }
        
        
    }
    
    
    
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        Function f = new Function();
        ResultSet rs = null;
        String pn = "name";
        String pp = "price";

        rs = f.find(txt_ID2.getText());
        try{
            if(rs.next()){
                txt_Name2.setText(rs.getString("name"));
                txt_Price2.setText(rs.getString("price"));
            }else
            {
                JOptionPane.showMessageDialog(null,"No Data For This ID");

            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_ID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ID2ActionPerformed

    private void txt_Name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Name2ActionPerformed

    private void btn_add_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_billActionPerformed
        // TODO add your handling code here:

        double per_unit = Double.parseDouble(txt_Price2.getText());
        double n_pieces = Double.parseDouble(txt_NP1.getText());
        double total = per_unit * n_pieces;
        txt_Per_UC.setText(String.valueOf(total));

        DefaultTableModel model =(DefaultTableModel) JTable_bill.getModel();
        model.addRow(new Object[]{txt_ID2.getText() , txt_Name2.getText() , txt_Price2.getText() , txt_NP1.getText(), txt_Per_UC.getText()});

        int rowsCount = JTable_bill.getRowCount();
        double sum=0.0;
        for(int i=0;i<rowsCount; i++)
        {
            sum=sum+Double.parseDouble(JTable_bill.getValueAt(i,4).toString());
            txt_sum.setText(String.valueOf(sum));
        }
    }//GEN-LAST:event_btn_add_billActionPerformed

    private void txt_NP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NP1ActionPerformed

    private void txt_sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sumActionPerformed

    private void btn_Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Exit1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_Exit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window_first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window_first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window_first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window_first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window_first().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Choose_Image;
    private javax.swing.JTable JTable_Products;
    private javax.swing.JTable JTable_bill;
    private javax.swing.JButton btn_BS;
    private javax.swing.JButton btn_DB;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Exit1;
    private javax.swing.JButton btn_First;
    private javax.swing.JButton btn_Insert;
    private javax.swing.JButton btn_Last;
    private javax.swing.JButton btn_Next;
    private javax.swing.JButton btn_Previous;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_add_bill;
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_background1;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_price;
    private javax.swing.JTextField txt_ID2;
    private javax.swing.JTextField txt_NP1;
    private javax.swing.JTextField txt_Name2;
    private javax.swing.JTextField txt_Per_UC;
    private javax.swing.JTextField txt_Price2;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_sum;
    // End of variables declaration//GEN-END:variables
}
